mqtt:
  sensor:
    - name: "lan2_gpon_in_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.status_lan_info['DEV.ETH.IF2'].InBytes | int }}"
      
    - name: "lan2_gpon_out_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.status_lan_info['DEV.ETH.IF2'].OutBytes | int }}"
      
    - name: "wifi24_gpon_in_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.wlan_client_configdrv_id['DEV.WIFI.AP1'].TotalBytesReceived | int }}"
      
    - name: "wifi24_gpon_out_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.wlan_client_configdrv_id['DEV.WIFI.AP1'].TotalBytesSent | int }}"
      
    - name: "wifi50_gpon_in_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.wlan_client_configdrv_id['DEV.WIFI.AP5'].TotalBytesReceived | int }}"
      
    - name: "wifi50_gpon_out_bytes"
      state_topic: "zte/gpon/f670l/local_net_status"
      unit_of_measurement: "bytes"
      value_template: "{{ value_json.wlan_client_configdrv_id['DEV.WIFI.AP5'].TotalBytesSent | int }}"